Fixed Sphinx/docutils error on Python 2.7
Details:

* Fixes the issue that on Python 2.7, running Sphinx fails with:

    File ".../site-packages/sphinx/util/nodes.py", line 94, in apply_source_workaround
      for classifier in reversed(node.parent.traverse(nodes.classifier)):
    TypeError: argument to reversed() must be a sequence

  by pinning docutils to <0.17 for Python==2.7. Note that Sphinx itself
  already ins docutils to <0.18 on most and to <0.17 on some versions, but
  on python 2.7, the pip version that is used still has the "legacy" package
  version resolver that ignores version constraint in package dependencies.

* Fixes the inconsistency that the minimum level of docutils was stated
  only in the minimum-constraints.txt file but not in the dev/rtd requirements
  files.

* Requiring a higher version of Sphinx for py>=3.5

* Excluding Sphinx 4.0.0 due to incompatibility with autodocsumm.

Signed-off-by: Andreas Maier <andreas.r.maier@gmx.de>