Test: Fixed issue with virtualenv raising AttributeError during installtest on py34
Details:

* virtualenv raised AttributeError: 'Path' object has no attribute 'write_bytes'
  during 'make installtest' on Python 3.4 since a few days.
  This had already been reported as https://github.com/pypa/virtualenv/issues/1963.
  This change fixes that by excluding virtualenv 20.0.32.
  To avoid an earlier issue where virtualenv did not install pop on Python 3.4,
  virtualenv 20.0.19 was also excluded.

Signed-off-by: Andreas Maier <andreas.r.maier@gmx.de>