Fixed dependency error with importlib-metadata on Python 3.8
Details:

* Since today, virtualenv failed with:
    AttributeError: 'Context' object has no attribute 'pattern'
  causing the installtest to fail.

  It turned out that uninstalling the importlib-metadata package solved the
  problem. That package was stated in our requirements files to be needed by
  tox 3.14 on Python <= 3.8. However, on Python 3.8 it is already in the base
  Python and not needed as a package. Uninstalling importlib-metadata solved
  the problem. It turned out that tox 3.x requires importlib-metadata only on
  Python < 3.8. It is not clear why this error showed up only starting today.
  Searching for packages released today (2021-07-18) did not reveal anything.

  This change fixes the problem by changing python_version <= '3.8' to < '3.8'
  on importlib-metadata inthe requirements files.

Signed-off-by: Andreas Maier <andreas.r.maier@gmx.de>